FROM owlab/debian-jessie-arm64
MAINTAINER Hun Jae Lee <hunjae.lee@gmail.com>

ENV GOLANG_VERSION 1.6.3
ENV GOPATH /go
ENV ARCHIVE_NAME go$GOLANG_VERSION.linux-arm64.tar.gz

COPY $ARCHIVE_NAME .

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    			g++ \
			gcc \
			libc6-dev \
			make \
    && rm -rf /var/lib/apt/lists/* \
    && tar -C /usr/local -zxvf $ARCHIVE_NAME \
    && rm $ARCHIVE_NAME \
    && mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
ENV GOROOT /usr/local/go

WORKDIR $GOPATH
